name: Build
on:
  push:
    branches: [ main ]

jobs:
  pybuild:
    runs-on: ubunto-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - uses: actions/setup-python@v6.1.0
      - with:
         python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: pyhton app.py
      - run: echo"Success"
